[package]
name = "bridge"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
aptos_token = "0x3"
bridge = "_"

[dependencies]
layerzero = { local = "../../layerzero" }
AptosToken = { local = "../../deps/aptos-core/aptos-move/framework/aptos-token" }
AptosFramework = {{ local = "../../deps/aptos-core/aptos-move/framework/aptos-framework" }